# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
cover:
  - platform: template
    covers:
      volet_pacome_force:
        friendly_name: "Volet All"
        device_class: shutter
        open_cover:
          action: rfplayer.send_command
          data:
            command: "ON"
            protocol: X2DSHUTTER
            device_address: C1
            automatic_add: false
        close_cover:
          action: rfplayer.send_command
          data:
            command: "OFF"
            protocol: X2DSHUTTER
            device_address: C1
            automatic_add: false
        stop_cover:
          action: rfplayer.send_command
          data:
            command: "STOP"
            protocol: X2DSHUTTER
            device_address: C1
            automatic_add: false
      volet_salon_force:
        friendly_name: "Volet Salon"
        device_class: shutter
        open_cover:
          action: rfplayer.send_command
          data:
            command: "ON"
            protocol: X2DSHUTTER
            device_address: C9
            automatic_add: false
        close_cover:
          action: rfplayer.send_command
          data:
            command: "OFF"
            protocol: X2DSHUTTER
            device_address: C9
            automatic_add: false
        stop_cover:
          action: rfplayer.send_command
          data:
            command: "STOP"
            protocol: X2DSHUTTER
            device_address: C9
            automatic_add: false
      volet_pierre_force:
        friendly_name: "Volet Pierre"
        device_class: shutter
        open_cover:
          action: rfplayer.send_command
          data:
            command: "ON"
            protocol: X2DSHUTTER
            device_address: C2
            automatic_add: false
        close_cover:
          action: rfplayer.send_command
          data:
            command: "OFF"
            protocol: X2DSHUTTER
            device_address: C2
            automatic_add: false
        stop_cover:
          action: rfplayer.send_command
          data:
            command: "STOP"
            protocol: X2DSHUTTER
            device_address: C2
            automatic_add: false
      volet_hanae_force:
        friendly_name: "Volet Hanae"
        device_class: shutter
        open_cover:
          action: rfplayer.send_command
          data:
            command: "ON"
            protocol: X2DSHUTTER
            device_address: C3
            automatic_add: false
        close_cover:
          action: rfplayer.send_command
          data:
            command: "OFF"
            protocol: X2DSHUTTER
            device_address: C3
            automatic_add: false
        stop_cover:
          action: rfplayer.send_command
          data:
            command: "STOP"
            protocol: X2DSHUTTER
            device_address: C3
            automatic_add: false
      volet_sacha_force:
        friendly_name: "Volet Sacha"
        device_class: shutter
        open_cover:
          action: rfplayer.send_command
          data:
            command: "ON"
            protocol: X2DSHUTTER
            device_address: C4
            automatic_add: false
        close_cover:
          action: rfplayer.send_command
          data:
            command: "OFF"
            protocol: X2DSHUTTER
            device_address: C4
            automatic_add: false
        stop_cover:
          action: rfplayer.send_command
          data:
            command: "STOP"
            protocol: X2DSHUTTER
            device_address: C4
            automatic_add: false
      volet_cuisine_force:
        friendly_name: "Volets Cuisine"
        device_class: shutter
        open_cover:
          action: rfplayer.send_command
          data:
            command: "ON"
            protocol: X2DSHUTTER
            device_address: C8
            automatic_add: false
        close_cover:
          action: rfplayer.send_command
          data:
            command: "OFF"
            protocol: X2DSHUTTER
            device_address: C8
            automatic_add: false
        stop_cover:
          action: rfplayer.send_command
          data:
            command: "STOP"
            protocol: X2DSHUTTER
            device_address: C8
            automatic_add: false
      volet_ami_force:
        friendly_name: "Volet chambre ami"
        device_class: shutter
        open_cover:
          action: rfplayer.send_command
          data:
            command: "ON"
            protocol: X2DSHUTTER
            device_address: C7
            automatic_add: false
        close_cover:
          action: rfplayer.send_command
          data:
            command: "OFF"
            protocol: X2DSHUTTER
            device_address: C7
            automatic_add: false
        stop_cover:
          action: rfplayer.send_command
          data:
            command: "STOP"
            protocol: X2DSHUTTER
            device_address: C7
            automatic_add: false
      volet_ami2_force:
        friendly_name: "Volet chambre ami2"
        device_class: shutter
        open_cover:
          action: rfplayer.send_command
          data:
            command: "ON"
            protocol: X2DSHUTTER
            device_address: C6
            automatic_add: false
        close_cover:
          action: rfplayer.send_command
          data:
            command: "OFF"
            protocol: X2DSHUTTER
            device_address: C6
            automatic_add: false
        stop_cover:
          action: rfplayer.send_command
          data:
            command: "STOP"
            protocol: X2DSHUTTER
            device_address: C6
            automatic_add: false

homekit:
  - name: ⚡ Divers
  - port: 2001
    filter:
      include_entities:
        - light.lumiere_5
        - light.lumiere_3
        - light.inter_bas_couloir_haut
        - light.escalier_bas
        - light.inter_couloir

  - name: 🛏️ Invites
  - port: 2002
    filter:
      include_entities:
        - cover.volet_ami2_force
        - light.lumiere_chambre_ami_2
        - switch.x2d_a1
        - cover.volet_ami_force
        - light.lumiere_chambre_ami_1

  - name: 🎬 Cinema
  - port: 2003
    filter:
      include_entities:
        - light.video_projecteur_3
        - light.video_projecteur_2
        - light.video_projecteur_1
        - switch.radiateur_home_cinema
        - light.salle_de_jeux
        - media_player.home_cinema

  - name: 🧺 Buanderie
  - port: 2004
    filter:
      include_entities:
        - light.0xf0d1b800001b0f66

  - name: 🚿 Salles de Bain
  - port: 2005
    filter:
      include_entities:
        - light.lumiere_sdb_bas_miroir
        - light.lumiere_sdb_bas
        - light.sdb_haut_2
        - light.sdb_haut
        - media_player.salle_de_bain

  - name: 🎀 Chambre Chiara
  - port: 2006
    filter:
      include_entities:
        - light.lumiere_chiara_3
        - light.lumiere_chiara_2
        - light.lumiere_chiara_1

  - name: 🌸 Chambre Hanae
  - port: 2007
    filter:
      include_entities:
        - cover.volet_hanae_force
        - light.plafond_hanae

  - name: ⚽ Chambre Sacha
  - port: 2008
    filter:
      include_entities:
        - cover.volet_sacha_force
        - light.lumiere_sacha

  - name: Chambre Pacome
  - port: 2009
    filter:
      include_entities:
        - sensor.0xa4c138e86f6207da_temperature
        - switch.radiateur_pacome
        - light.switch_pacome
        - light.lampe_yaya_de_pacome
        - light.meuble_pacome_2
        - cover.volet_pacome_force
        - light.bureau_pacome

  - name: Chambre Pierre
  - port: 2010
    filter:
      include_entities:
        - light.spot_bureau_3
        - light.spot_bureau_2
        - light.0x403059fffef097e2
        - light.0xa46dd4fffe677161
        - light.0x94deb8fffeb20706
        - light.lumiere_dressing
        - light.chambre_pierre
        - media_player.chambre_pierre

  - name: Salon
  - port: 2011
    filter:
      include_entities:
        - switch.salle_a_manger
        - switch.lampe_evier
        - light.lumieres_bar
        - light.lumieres_cuisine
        - media_player.piece_a_vivre

  - name: 🏡 Espace de Vie
  - port: 2012
    filter:
      include_entities:
        - switch.salle_a_manger
        - switch.lampe_evier
        - light.lumieres_bar
        - light.lumieres_cuisine
        - media_player.piece_a_vivre

